# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tm < Formula
  desc "Time Calculator."
  homepage "https://github.com/winebarrel/tm"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/tm/releases/download/v1.3.2/tm_1.3.2_darwin_amd64.tar.gz"
      sha256 "ccdfd77670b69391fbd18f6904ac4f6e8fd72e07a80caebdef1b76fbc8c7466f"

      def install
        bin.install 'tm'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/tm/releases/download/v1.3.2/tm_1.3.2_darwin_arm64.tar.gz"
      sha256 "876bae7f10115e82270799f156ba06575fbdd60f4127f956944f1c3634e8ba6a"

      def install
        bin.install 'tm'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/tm/releases/download/v1.3.2/tm_1.3.2_linux_arm64.tar.gz"
      sha256 "d2423723fdb19ef0d60d6b518e6650452079b807bb78676a9d6e8b66b251305d"

      def install
        bin.install 'tm'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/tm/releases/download/v1.3.2/tm_1.3.2_linux_amd64.tar.gz"
      sha256 "0d526ca7f8ff41867e497ca331e493de545c4165b89745ba416dd8792b7397c7"

      def install
        bin.install 'tm'
      end
    end
  end
end
