# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tm < Formula
  desc "Time Calculator."
  homepage "https://github.com/winebarrel/tm"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/tm/releases/download/v1.3.0/tm_1.3.0_darwin_arm64.tar.gz"
      sha256 "56060bfdf036ab7f4a5a801c8bec8a6101917601ca86900c3679cd6bfbce25f5"

      def install
        bin.install 'tm'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/tm/releases/download/v1.3.0/tm_1.3.0_darwin_amd64.tar.gz"
      sha256 "4f4e366ab3d99f211d824b5bcb3a659f8bce9188ef39b826fc6655520d50c6df"

      def install
        bin.install 'tm'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/tm/releases/download/v1.3.0/tm_1.3.0_linux_arm64.tar.gz"
      sha256 "376fad84e1318bdd4307f3ea0a640846ea9eddf2606d6bacfcf1dc070c4ae345"

      def install
        bin.install 'tm'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/tm/releases/download/v1.3.0/tm_1.3.0_linux_amd64.tar.gz"
      sha256 "1793238dd12519ffe9aef0112f3c6fa9a6520d5e59575cf5780eb0875b68ac85"

      def install
        bin.install 'tm'
      end
    end
  end
end
