# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tm < Formula
  desc "Time Calculator."
  homepage "https://github.com/winebarrel/tm"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/tm/releases/download/v1.0.0/tm_1.0.0_darwin_amd64.tar.gz"
      sha256 "332bcf074dc5083cedd7c3697819f9069fcf30905e0782c057bb98eab8d144f3"

      def install
        bin.install 'tm'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/tm/releases/download/v1.0.0/tm_1.0.0_darwin_arm64.tar.gz"
      sha256 "c40809f6ec3a8106280743794d7e4a16d97eef2739fa0e12b8a47304ee5b8084"

      def install
        bin.install 'tm'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/tm/releases/download/v1.0.0/tm_1.0.0_linux_arm64.tar.gz"
      sha256 "582589deecb9fe074a7dafd8e5003c34eea3c83b37688c66218edb78c15eff8c"

      def install
        bin.install 'tm'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/tm/releases/download/v1.0.0/tm_1.0.0_linux_amd64.tar.gz"
      sha256 "d98c808a3238768f6f748a2264efc0f32fe37bf42e9c988a52b41ec67f36cb82"

      def install
        bin.install 'tm'
      end
    end
  end
end
